= Introduction to measurement theory
:stem:

== Introduction to the course
This course is based on Fred Roberts’ book, https://doi.org/10.1017/CBO9780511759871[Measurement Theory]. Most of the exercices come from his book.

=== What
* Measurement: represent aspects of a concrete system abstractly, using numbers, vectors…
* Measurement theory: represent relations among objects using relations among numbers
* Representability theorems
* Measurement also includes metrology
* Measurement theory ≠ Measure theory (which does not start from supposedly observable relations)

=== Examples

* Measure pollution
* Organize society so as to maximize global utility (https://en.wikipedia.org/wiki/The_Methods_of_Ethics[The Methods of Ethics] by Henry Sidgwick)
* Distribute resources fairly (https://en.wikipedia.org/wiki/A_Theory_of_Justice[A Theory of Justice] by John Rawls, https://global.oup.com/academic/product/natural-justice-9780199791484[Natural Justice] by Ken Binmore)
* Reduce inequality
* Satisfy citizen’s preferences

=== Motivation
* Introduce rigorous reasoning in decision making
* Use mathematical language for precision
* Mathematics only takes care of a small part! (Also: political science, sociology, psychology, economics…)
* A rigorous introduction to some fundamental constructs of mathematics

=== Organization
* S1, S2 (, S3) : Relations
* S3, S4 : Fundamental measurement
* S5 : exam
* S6 : A simple representation theorem
* S7 : Involving some intransitivity
* S8 : exam

Each lecture: about 1h theory, 1h practice

* Exams stem:[e]: average of both exams (equal weight)
* Participation stem:[p]: each lecture, 0, + (significant intervention) or ++ (clever or committed intervention)
* Notes in Asciidoc format through GitHub stem:[n] (talk to me first)
* Final grade: weighted average of stem:[e] (9 points), stem:[max(e, p)] (3 points), stem:[max(e, n)] (up to 8 points)

https://github.com/oliviercailloux/Teaching/blob/main/README.adoc#take-notes[Take notes]

=== Primitive notions
* Set, stem:[∅]
* stem:[∈]
* stem:[=]
* Logic operators: stem:[¬], stem:[∨], stem:[∧], stem:[⇒], stem:[⇔], stem:[∃], stem:[∀]
* stem:[∉]
* Produce other sets: stem:[{x ∈ A | …}], stem:[∪], stem:[∩], stem:[℘], stem:[×]
* Also: primitive elements
* Ordered pair, sets thereof, domain stem:[𝒟], image stem:[𝓘], field stem:[ℱ]

References

* Refer to the delightful book of Halmos: https://doi.org/10.1007%2F978-1-4757-1645-0[Naive set theory].
* For more context, read https://www.logicomix.com/[Logicomix].

== Relations and properties of relations
=== Definition and some properties
* Relation from stem:[A] to stem:[A]: subset of stem:[A × A] (homogeneous relation, our focus)
* Also called Binary relation on stem:[A]
* Relations between objects, persons, …
* Notation: stem:[a R b] means stem:[(a, b) ∈ R]

Directed graph

==== Properties of relations
In this document, properties of a relation stem:[R] are expressed with implicit qualifiers: a non bound letter stem:[x] is implicitly prefixed with stem:[∀x ∈ ℱ(R)]

==== Transitivity
Transitive relation: stem:[a R b R c ⇒ a R c]

* Transire, to pass to the other side, convey an action
* I push my car VS I sleep in my car: push used transitively
* Relates a to c through b

==== Reflexivity
stem:[a R a]

==== Irreflexivity
stem:[¬(a R a)]

A relation that is not reflexive is not necessarily irreflexive (similarly for other properties).

==== Preorder
* Transitive and reflexive
* (Also called: partial preorder, quasi order)

Here: mostly transitive and reflexive relations

Hasse diagram: stem:[a R b, a ≠ b], corresponds to a line descending from a to b.

==== Symmetry
stem:[a R b ⇒ b R a]

==== Asymmetry
stem:[a R b ⇒ ¬(b R a)]

==== Antisymmetry
stem:[a ≠ b ∧ a R b ⇒ ¬(b R a)]

==== Exercices
See https://oliviercailloux.github.io/Introduction-to-measurement-theory/Ex1.html[Exercices S1].

=== A zoo of relations
==== Equivalence
An equivalence relation is a transitive (, reflexive) and symmetric relation.

Each element in an equivalence relation has an associated equivalence class. The set of equivalence classes, called the quotient by stem:[R], is denoted by stem:[ℱ(R) // R]. It partitions (disjointly covers) stem:[ℱ(R)].

* Symmetric part of a relation stem:[R]: stem:[sym(R) = {(a, b) ∈ R | (b, a) ∈ R}]
* The symmetric part of a preorder stem:[R] is an equivalence relation
* Intuitively speaking, a preorder defines equivalence classes (namely, its quotient by stem:[sym(R)]) and orders them (possibly partially)
* That ordering is a relation on its quotient by stem:[sym(R)] and is called the reduction of a preorder stem:[R]
* Formally, the reduction of stem:[R] is defined as stem:[{(a^***, b^***) ∈ (ℱ(R) // sym(R))² | ∃ a ∈ a^***, b ∈ b^*** | a R b}].

// stem:[{a ∈ A | ∃x ∈ X | x < a}]

// === Converse
// Optional

// === Negative transitivity
// Optional

==== Side-uniqueness, ontoness
* Right-unique: stem:[a R b ∧ a R c ⇒ b = c]
* A right-unique relation is a function from stem:[𝒟(R)] to stem:[𝓘(R)]; we can write stem:[R(a)] to denote the single stem:[b ∈ 𝓘(R)] such that stem:[a R b].
* Onto stem:[Y] (right-total over stem:[Y]): stem:[Y = 𝓘(R)]
* Left-unique (injective): stem:[b R a ∧ c R a ⇒ b = c]

==== Weak completeness
stem:[a ≠ b ⇒ a R b ∨ b R a]

==== Order
* Transitive, reflexive, antisymmetric
* (Also called: partial order)

Intuitively: a (possibly partial) ranking without ties

==== Complete preorder
* Transitive, reflexive, weakly complete
* (Often called: weak order)

* Intuitively: a ranking with ties
* The symmetric part of a complete preorder is an equivalence relation
* A complete preorder defines equivalence classes and orders them completely

==== Complete order
* Transitive, reflexive, weakly complete, antisymmetric
* (Also called: simple order, linear order, total order)

Intuitively: a ranking without ties

The reduction of a complete preorder stem:[R] is a complete order on stem:[ℱ(R) // sym(R)].

// === Strict order
// Transitive and irreflexive
// (Often called: strict partial order)

==== Generalisation to binary operations
* A relation from stem:[X] to stem:[Y] is a subset of stem:[X × Y]. It is non homogeneous when stem:[X ≠ Y].
* A binary operation stem:[α] on stem:[A] is a right-unique relation from stem:[A × A] to stem:[A] whose domain is stem:[(A × A)].
* It can be viewed as a function from stem:[A × A] to stem:[A]; we can write stem:[a α b] to denote the single stem:[c ∈ 𝓘(α)] such that stem:[(a, b) α c].
* Examples: stem:[+], stem:[×] on stem:[ℕ].

==== Note about terminology
For many authors (excluding Halmos but including Roberts), the set on which stem:[R] is defined is exogenous, thus a relation is a pair stem:[(A, R)] with stem:[R ⊆ A²] (hence stem:[ℱ(R) ⊆ A]). This allows for the possibility that stem:[ℱ(R) ≠ A]. Weak completeness is then defined as stem:[∀ a ≠ b ∈ A: a R b ν b R a]. Similarly, other definitions (such as reflexivity) then differ from those given here. In this document, we assume stem:[A] is chosen equal to stem:[ℱ(R)], in which case the definitions coincide.

==== Exercices
See https://oliviercailloux.github.io/Introduction-to-measurement-theory/Ex2.html[Exercices S2].

== Fundamental measurement
* We want to assign numbers to reflect some properties of some systems.
* Given relation stem:[R] “looks shorter than” on stem:[A = {a, b, …}], can we assign numbers stem:[f(a)] so that stem:[f(a) < f(b) ⇔ a R b]?
* Similarly for relations “preferred to”, “day with better air quality”.

* We might also want to reflect operations such as “combining”: consider “is lighter”, with A including combined objects; can we then assign numbers stem:[f(.)] so that when stem:[a] and stem:[b] combined are lighter than stem:[c], stem:[f(a) + f(b) < f(c)]; or so that when stem:[c] denotes the combination of stem:[a] and stem:[b], stem:[f(a) + f(b) = f(c)]?
* Similarly for relation “preferred to” on sets of objects.

* Relation stem:[R] on stem:[A] corresponds to relation stem:[T] on stem:[ℝ] through function stem:[f] from stem:[A] to stem:[ℝ]: stem:[a R b ⇔ f(a) T f(b)].
* (If stem:[T] is restricted to the image of stem:[f], it is determined uniquely by stem:[f] and stem:[R], in other words, stem:[R] never corresponds to two relations stem:[T1 ≠ T2] through a single function stem:[f] when stem:[ℱ(T1) = ℱ(T2) = 𝓘(f)]. Proof: if R corresponds to T1 and T2 through f with ℱ(T1) = ℱ(T2) = 𝓘(f), then x T1 y iff a R b, for any a ∈ f-1(x), b ∈ f-1(y), iff x * T2 y thus T1 = T2.)
* Operation stem:[⊙] on stem:[A] corresponds to operation stem:[α] on stem:[ℝ] through function stem:[f] from stem:[A] to stem:[ℝ]: stem:[f(a ⊙ b) = f(a) α f(b)].
* stem:[R] is homomorphic to stem:[T] iff it corresponds to stem:[T] through some function stem:[f].
* stem:[(R, ⊙)] is homomorphic to stem:[(T, α)] iff stem:[R] corresponds to stem:[T] and stem:[⊙] to stem:[α] through the same function stem:[f].
* More generally, stem:[(R, {⊙_i})] is homomorphic to stem:[(T, {α_i})] iff stem:[R] corresponds to stem:[T] through some function stem:[f] and each stem:[⊙_i] corresponds to stem:[α_i] through stem:[f].
* The tuple stem:[(f, (T, {α_i}))] is called a measurement scale for stem:[(R, {⊙_i})].
// (If f is a scale, 
// ∀x, y ∈ 𝓘(f): f-1(x) × f-1(y) ⊆ R ν f-1(x) × f-1(y) ∩ R = ∅ 
// and
// f(f-1(x) o f-1(y)) is a singleton.)

=== Representation theorem
* A theorem of the form: under such conditions on stem:[(R, {⊙_i})], the system is homomorphic to stem:[(T, {α_i})].
* Constructive proof: gives a procedure to build a scale stem:[f].
* Intuitively: transitivity of stem:[R] is required for homomorphism to stem:[≥].

Uniqueness: to determine properties of the numbers that transfer to our observations.

=== Homomorphisms and scale types
* Number of persons VS height of a person
* Ratio of weight VS ratio of t°

Given stem:[(R, {⊙_i})] corresponding to stem:[(T, {α_i})] through stem:[f], admissible transformation stem:[φ] from stem:[f(A)] to stem:[ℝ] (thus stem:[φ ∘ f] from stem:[A] to stem:[ℝ]): stem:[(R, {⊙_i})] corresponds to stem:[(T, {α_i})] through stem:[φ ∘ f].

// R has a regular homomorphism to T: it has a homomorphism to T and for every scales (f, (T, {α_i})), (g, (T, {α_i})), for some φ, g = φ ∘ f.
stem:[R] has a regular homomorphism to stem:[T]: it has a homomorphism to stem:[T] and for every scales stem:[(f, (T, {α_i}))], stem:[(g, (T, {α_i}))], stem:[f(a) = f(b) ⇔ g(a) = g(b)].

Scale type depends on the class of admissible transformations φ.

* Absolute: φ(x) = x; Counting
* Ratio: φ(x) = rx with r > 0; Mass
* Interval: φ(x) = rx + s with r > 0; T° without absolute zero
* Ordinal: strictly monotone increasing transformation; Ordinal preference, Mohs scale of hardness
* Nominal: any bijection; Labels

// Example using air pollution might be interesting but is not hugely convincing concerning meaningfulness.

== Representation of complete preorders
=== Arithmetic and infinite sets
* Successor of stem:[s]: stem:[s ⋃ {s}]
* Axiom of infinity: ∃ successor set A
* ℕ: intersection of all successor sets in A
* Permits induction, which we use to define addition of zero, then addition of one, …
* Finite set: bijection with an element of ℕ

=== The ≥ relation
* If R is a complete preorder and ℱ(R) is finite, it is homomorphic to ≥.
* Necessary and sufficient conditions.
* Can we relax finiteness?

Scale type: ordinal

== When indifference is not transitive
=== Requirement of transitivity
* R homomorphic to ≥ requires transitivity.
* Define I as the symmetric part of R.
* R homomorphic to ≥ requires I to be transitive.

=== Examples
Detection threshold

* Coffee with sugar
* Noise level

Incomparability

* Pony VS bicycle (https://doi.org/10.2307/2224802[Armstrong, 1939])
* Good job VS apartment
* Reform social security: better for end-of-life VS better life expectancy

=== Representation
* x ≥δ y: x ≥ y - δ
* Constant threshold δ

Won’t do for incomparability: Pony* ≻ Pony, Bicycle ≽ Pony*, Bicycle* ≻ Bicycle but Pony ≽ Bicycle*.

=== Completed semiorder
≽ is a completed semiorder: weakly complete and reflexive and satisfies

* S2: a ≽ b ∧ c ≽ d ⇒ c ≽ b ∨ a ≽ d
* S3: a ≽ b ≽ c ⇒ a ≽ d ∨ d ≽ c

Covers: a W c iff (d ≽ a ⇒ d ≽ c) ∧ (c ≽ d ⇒ a ≽ d).

* S2 and S3 are together equivalent to ∀a ≻ b ≽ c: a W c.
* S2 and S3 are together equivalent to ∀a ≽ b ≻ c: a W c.

Equivalently:

* S2 can be written ¬(a ≽ b ≻ c ≽ d ≻ a) and S3 can be written ¬(c ≻ d ≻ a ≽ b ≽ c), writing x ≻ y iff ¬(y ≽ x).
* S2 can be written ¬(d ≽ a ≻ b ≽ c ≻ d) and S3 can be written ¬(d ≻ a ≻ b ≽ c ≽ d).
* S2 can be written ∀a ≻ b ≽ c: (d ≽ a ⇒ d ≽ c) and S3 can be written ∀a ≻ b ≽ c: (c ≽ d ⇒ a ≽ d).
* S2 can be written ¬(c ≻ d ≽ a ≻ b ≽ c) and S3 can be written ¬(b ≽ c ≽ d ≻ a ≻ b).
* Renaming, S2 can be written ¬(d ≻ a ≽ b ≻ c ≽ d) and S3 can be written ¬(d ≽ a ≽ b ≻ c ≻ d).
* Thus, S2 can be written ∀a ≽ b ≻ c: (c ≽ d ⇒ a ≽ d) and S3 can be written ∀a ≽ b ≻ c: (d ≽ a ⇒ d ≽ c).
* By contrapositive, using these two equivalences, ¬(a W c) ⇒ ∀b: (b ≽ c ⇒ b ≽ a) ∧ (a ≽ b ⇒ c ≽ b), in other words, ¬(a W c) ⇒ c W a.

If ≽ is a completed semiorder, then W is a complete preorder.
Proof. Transitive: If c ≽ d then by b W c ≽ d we get b ≽ d and by a W b ≽ d we get a ≽ d. It is strongly complete, as seen just above.

If ≽ is a completed semiorder, then c W b ⇒ c ≽ b (and b ≻ c ⇒ b W c).
Proof. c W b ⇒ (c ≽ c ⇒ c ≽ b) ⇒ c ≽ b (and use contrapositive and completeness of W).

Thm. If ≽ is a completed semiorder, then a W b W c ~ a ⇒ a ~ b ~ c, writing x ~ y iff x ≽ y ≽ x.
Pr. Rewrite the hypothesis as c ≽ a W b W c ≽ a and obtain c ≽ b ≽ a by definition of W and a ≽ b ≽ c using W ⊆ ≽.

=== Representation theorem
If ≽ is a completed semiorder, then there exists a function f from ℱ(≽) to ℝ such that stem:[f(a) ≥_1 f(b) ⇔ a ≽ b].

=== Related applications
* Liberal to conservative politics
* Psychological stages of development
* Chronology of archeological artifacts
