= Exercices S1
:lang: fr

== Sororité
Imaginez que dans cette classe se trouve trois familles de deux ou trois enfants chacune.
// (imaginez comme vous voulez qui en est membre). 
Nos familles fictives volontaires : {Laure, Laureline}, {Agnès, Blanche}, {Roxane, Anna, Charline}.
Les autres sont issus de familles distinctes.

Définissez la relation représentant « sœur de » dans cette classe, au sens intuitif du terme, c’est-à-dire définissant une relation irréflexive. Démontrez qu’elle est irréflexive.
Démontrez que cette relation n’est pas transitive.

== De mêmes parents
Poursuivons l’hypothèse précédente de familles fictives dans notre classe.

Définissez la relation https://fr.wikipedia.org/w/index.php?title=S%C5%93ur&oldid=223147623[représentant] « personne de sexe féminin née des mêmes parents » dans cette classe. Démontrez qu’elle est réflexive.
Argumentez informellement de sa transitivité.
Imaginez d’autres familles fictives dans la classe qui rendraient la relation non réflexive.

// Définissez la relation sur un sous-ensemble de personnes pour lui faire satisfaire une propriété supplémentaire au choix vue en cours.

== Gauchisme
Définissez la relation représentant « assis à la gauche de et sur la même rangée » dans cette classe.
Quelles propriétés satisfait-elle ?

== Gauchisme relâché
Définissez la relation représentant « plus proche ou aussi proche du mur de gauche » dans cette classe.
Quelles propriétés satisfait-elle ?

== Opérations sur les relations
Avec stem:[S] et stem:[G] les relations ci-dessus (dans une certaine acception de votre choix), calculez stem:[S ∪ G] et stem:[S ∩ G]. Pour quelles façons de comprendre ces relations a-t-on stem:[S ∪ G = ∅] ? Même question pour stem:[S ∩ G]. Représentez ces relations graphiquement selon la méthode la plus appropriée.

== Antisymétrie
Démontrer : une relation est asymétrique ssi elle est irréflexive et antisymétrique.

Préciser et démontrer : une relation symétrique n’est pas asymétrique, sauf si…

Préciser et démontrer : une relation asymétrique n’est pas symétrique, sauf si…

Caractériser les relations qui sont à la fois symétriques et antisymétriques.

== Inverse
Définissons l’inverse de stem:[R] comme : stem:[R^{-1} = {(b, a) | (a, b) ∈ R}].
Montrer que stem:[R^{-1}] est réflexive ssi stem:[R] l’est.
Qu’en est-il de ces autres propriétés ?

* Irréflexivité
* Symétrie
* Antisymétrie
* Transitivité

== Opérations & propriétés
Si stem:[R] et stem:[S] sont réflexives, stem:[R ∩ S] est-elle réflexive ?
Qu’en est-il de ces autres propriétés ?

* Irréflexivité
* Symétrie
* Antisymétrie
* Transitivité

== À un près
Définissons stem:[R = {(x, y) | x, y ∈ ℝ ∧ x > y + 1}]. Quelles propriétés satisfait stem:[R] ?

== Expériences
Effectuez les exercices 13 et 16 du livre de Roberts, pages 23 et 24, considérant nos cinq propriétés favorites.
