= Solutions S1

== Sororité
- Relation : stem:[S_1 = {("Laure", "Laureline"), ("Laureline", "Laure"), ("Agnès", "Blanche"), ("Blanche", "Agnès"), ("Roxane", "Anna"), ("Anna", "Roxane"), ("Roxane", "Charline"), ("Charline", "Roxane"), ("Anna", "Charline"), ("Charline", "Anna")}]. Notons que les autres membres de la classe n’apparaissent pas dans cette relation : n’étant sœurs de personne, ils ne sont pas en relation avec qui que ce soit.
- Champ : stem:[ℱ(S_1) = {"Laure", "Laureline", "Agnès", "Blanche", "Roxane", "Anna", "Charline"}]. Notons que le champ n’inclut pas les autres membres de la classe, car stem:[ℱ(S_1)] ne contient que les éléments en relation avec au moins un autre élément.
- Il faut établir que stem:[∀a ∈ ℱ(S_1): (a, a) ∉ S_1], ce qui est immédiatement visible : stem:[("Laure", "Laure") ∉ S_1], stem:[("Laureline", "Laureline") ∉ S_1], stem:[("Agnès", "Agnès") ∉ S_1], stem:[("Blanche", "Blanche") ∉ S_1], stem:[("Roxane", "Roxane") ∉ S_1], stem:[("Anna", "Anna") ∉ S_1] et stem:[("Charline", "Charline") ∉ S_1].
- Il faut établir que stem:[∃a, b, c ∈ ℱ(S_1) | ¬(aS_1bS_1c ⇒ aS_1c)], autrement dit, que stem:[∃a, b, c ∈ ℱ(S_1) | aS_1bS_1c ∧ ¬(aS_1c)]. Considérons par exemple stem:[a = "Roxane", b = "Anna", c = "Roxane"]. Nous avons bien stem:["Roxane" S_1 "Anna" S_1 "Roxane"], mais pas stem:["Roxane" S_1 "Roxane"].

== De mêmes parents
- Relation : stem:[S_2 = {("Laure", "Laure"), ("Laureline", "Laureline"), ("Laure", "Laureline"), ("Laureline", "Laure"), ("Agnès", "Agnès"), ("Blanche", "Blanche"), ("Agnès", "Blanche"), ("Blanche", "Agnès"), ("Roxane", "Roxane"), ("Anna", "Anna"), ("Charline", "Charline"), ("Roxane", "Anna"), ("Anna", "Roxane"), ("Roxane", "Charline"), ("Charline", "Roxane"), ("Anna", "Charline"), ("Charline", "Anna"), ("Abigael", "Abigael"), ("Aliosha", "Aliosha"), ("Anna", "Anna"), …}]. Les points de suspension représentent toutes les paires de type stem:[(x, x)] où stem:[x] est une femme de la classe.
- Champ : stem:[ℱ(S_2)] contient toutes les femmes de la classe.
- Il faut établir que stem:[∀a ∈ ℱ(S_2): (a, a) ∈ S_2], ce qui est immédiatement visible : stem:["Laure" S_2 "Laure"], stem:["Laureline" S_2 "Laureline"], etc.
- La transitivité est satisfaite par stem:[S_2] car si stem:[a] est une femme née des mêmes parents que stem:[b], et si stem:[b] est une femme née des mêmes parents que stem:[c], alors stem:[a] est une femme née des mêmes parents que stem:[c]. (Notons que ce genre d’argumentation informelle peut se fourvoyer, comme illustre le fait qu’on aurait pu croire que la relation stem:[S_1] ci-dessus était transitive, ce qui échoue dans le cas de stem:[S_1] lorsque stem:[a = c].)
- La relation serait non réflexive si nous avions dans la classe une famille comportant au moins un homme et une femme, mettons Olivier frère de Cécile. Dans ce cas, stem:[("Cécile", "Olivier") ∈ S_2], donc stem:["Olivier" ∈ ℱ(S_2)], mais stem:[("Olivier", "Olivier") ∉ S_2].

== Gauchisme
Pour raccourcir la réponse, supposons qu’il n’y ait que six personnes et trois rangées dans notre classe : dans l’ordre de gauche à droite, rangée 1, stem:[("Laure", "Laureline", "Agnès")], rangée 2, stem:[("Blanche", "Roxane")], et rangée 3, stem:["Charline"] seule.

- Relation : stem:[G = {("Laure", "Laureline"), ("Laure", "Agnès"), ("Laureline", "Agnès"), ("Blanche", "Roxane")}].
- Champ : stem:[ℱ(G) = {"Laure", "Laureline", "Agnès", "Blanche", "Roxane"}]. Notons que "Charline" n’apparait pas dans le champ, n’étant assise à la gauche de personne.
- La relation n’est pas réflexive : informellement, il existe au moins une personne qui n’est pas assise à la gauche d’elle-même ; formellement, on a bien stem:[∃ a ∈ ℱ(G) | (a, a) ∉ G], par exemple stem:[("Laure", "Laure") ∉ G].
- La relation est irréflexive : informellement, personne n’est assis à la gauche de soi-même ; formellement, on a bien stem:[∀a ∈ ℱ(G): (a, a) ∉ G] puisque stem:[("Laure", "Laure") ∉ G], stem:[("Laureline", "Laureline") ∉ G], stem:[("Agnès", "Agnès") ∉ G], stem:[("Blanche", "Blanche") ∉ G] et stem:[("Roxane", "Roxane") ∉ G].
- La relation est transitive : informellement, si stem:[a] est assise à la gauche de stem:[b] et sur la même rangée que stem:[b], et si stem:[b] est assise à la gauche de stem:[c] et sur la même rangée que stem:[c], alors stem:[a] est effectivement assise à la gauche de stem:[c] et sur la même rangée que stem:[c] ; formellement, on a bien stem:[∀a, b, c ∈ ℱ(G): (aGbGc ⇒ aGc)], ce qui est équivalent à stem:[∀a, b, c | aGbGc: aGc], puisque seul le triplet stem:[a = "Laure", b = "Laureline", c = "Agnès"] satisfait stem:[aGbGc], et on a bien stem:["Laure" G "Agnès"].
- La relation n’est pas symétrique : formellement, on a bien stem:[∃a, b ∈ ℱ(G) | aGb ∧ ¬(bGa)], par exemple stem:["Laure" G "Laureline"] mais pas stem:["Laureline" G "Laure"].
- La relation est asymétrique : formellement, on a bien stem:[∀a, b ∈ ℱ(G): aGb ⇒ ¬(bGa)] puisque stem:[¬("Laureline" G "Laure")], stem:[¬("Agnès" G "Laure")], stem:[¬("Agnès" G "Laureline")] et stem:[¬("Roxane" G "Blanche")].
- La relation est antisymétrique : formellement, on a bien stem:[∀a ≠ b ∈ ℱ(G): aGb ⇒ ¬(bGa)], pour la même raison que pour l’asymétrie.
